import json
from fpdf import FPDF
import os

class ComparativePDF(FPDF):
    def header(self):
        self.set_font("helvetica", "B", 15)
        self.set_text_color(51, 51, 51)
        self.cell(0, 10, "Barista CI - Comparative Intelligence Report", border=False, ln=1, align="C")
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by Barista AI", 0, 0, "C")

def generate_comparative_pdf(json_file_path: str, output_pdf_path: str):
    if not os.path.exists(json_file_path):
        print(f"Error: JSON file not found at {json_file_path}")
        return

    with open(json_file_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    pdf = ComparativePDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    pdf.set_margins(15, 15, 15)

    def add_section_title(title):
        pdf.set_font("helvetica", "B", 14)
        pdf.set_text_color(41, 128, 185)
        pdf.cell(0, 10, title.upper(), border="B", ln=1)
        pdf.ln(3)

    def add_body_text(text):
        if not text:
            return
        pdf.set_font("helvetica", "", 11)
        pdf.set_text_color(50, 50, 50)
        # Handle some basic unsupported unicode chars
        clean_text = text.replace('\u2019', "'").replace('\u2018', "'").replace('\u201c', '"').replace('\u201d', '"').replace('\u2014', '-')
        pdf.multi_cell(0, 7, txt=clean_text)
        pdf.ln(4)

    # Title
    pdf.set_font("helvetica", "B", 18)
    pdf.set_text_color(44, 62, 80)
    title = data.get("report_title", "Comparative Intelligence Report")
    pdf.multi_cell(0, 10, txt=title.replace('\u2019', "'"), align="C")
    pdf.ln(10)

    # Executive Summary
    add_section_title("Executive Summary")
    add_body_text(data.get("executive_summary", ""))

    # Positioning
    add_section_title("Your Product Positioning")
    add_body_text(data.get("user_product_positioning", ""))

    # Competitors
    competitors = data.get("competitors", [])
    if competitors:
        pdf.add_page()
        add_section_title("Competitor Analysis")
        for comp in competitors:
            pdf.set_font("helvetica", "B", 12)
            pdf.set_text_color(44, 62, 80)
            pdf.cell(0, 8, f"{comp.get('name', 'Competitor')} ({comp.get('domain', '')})", ln=1)
            pdf.ln(2)
            
            pdf.set_font("helvetica", "B", 11)
            pdf.set_text_color(50, 50, 50)
            pdf.cell(0, 6, "Pricing Strategy:", ln=1)
            add_body_text(comp.get("pricing_strategy", "Unknown"))
            
            pdf.set_font("helvetica", "B", 11)
            pdf.set_text_color(50, 50, 50)
            pdf.cell(0, 6, "Key Features:", ln=1)
            for f_item in comp.get("key_features", []):
                add_body_text(f"• {f_item}")
                
            pdf.set_font("helvetica", "B", 11)
            pdf.set_text_color(50, 50, 50)
            pdf.cell(0, 6, "Strengths:", ln=1)
            for s_item in comp.get("strengths", []):
                add_body_text(f"• {s_item}")
                
            pdf.set_font("helvetica", "B", 11)
            pdf.set_text_color(50, 50, 50)
            pdf.cell(0, 6, "Weaknesses:", ln=1)
            for w_item in comp.get("weaknesses", []):
                add_body_text(f"• {w_item}")
                
            pdf.ln(5)

    # Recommendations
    pdf.add_page()
    add_section_title("Strategic Recommendations")
    for rec in data.get("recommendations", []):
        add_body_text(f"• {rec}")

    pdf.output(output_pdf_path)

if __name__ == "__main__":
    pass
